<?php

namespace src\utils;



const NOMBRES = [
    'Pau',
    'Unai',
    'Rafael',
    'Joel',
    'Alberto',
    'Pedro',
    'Raúl',
    'Aitor',
    'Santiago',
    'Rayan',
    'Pol',
    'Nil',
    'Noah',
    'Jan',
    'Asier',
    'Fernando',
    'Alonso',
    'Matías',
    'Biel',
    'Andrés',
    'Axel',
    'Ismael',
    'Martí',
    'Arnau',
    'Imran',
    'Luka',
    'Ignacio',
    'Aleix',
    'Alan',
    'Elías',
    'Omar',
    'Isaac',
    'Youssef',
    'Jon',
    'Teo',
    'Mauro',
    'Óscar',
    'Cristian',
    'Leonardo',
];

const APELLIDOS = [
    "Cuellar",
    "Martorell",
    "Mayoral",
    "Pedraza",
    "Mariscal",
    "Carrero",
    "Boix",
    "Ureña",
    "Camps",
    "Céspedes",
    "Girón",
    "Quiles",
    "Piqueras",
    "Guevara",
    "Zurita",
    "Revuelta",
    "Fidalgo",
    "Andújar",
    "Gamero",
    "Cañadas",
    "Mir",
    "Arellano",
    "Planas",
    "Parada",
    "Goñi",
    "Picazo",
    "Centeno",
    "Sales",
    "Perera",
    "Viera",
    "Lema",
    "Gordo",
    "Romo",
    "Guisado",
    "Riquelme",
    "Amor",
    "Rial",
    "Torregrosa",
    "Álamo",
    "Pico",
    "Vilches",
    "Quiroga",
    "Mera",
    "Frutos",
    "Mestre",
    "Amores",
    "Carrascosa",
    "Solana",
    "Palau",
    "Sabater",
    "Benavides",
    "Codina",
    "Botella",
    "Vegas",
    "Adán",
    "Seguí",
    "Gabarri",
    "Lora",
    "Calatayud",
    "Arnau",
    "de Dios",
    "Fonseca",
    "Palazón",
    "Quero",
    "Nevado",
    "Antúnez",
    "Novo",
    "Labrador",
    "Zhu",
    "Chico",
    "Parejo",
    "Nieves",
    "Hermoso",
    "Toledano",
    "Herraiz",
    "Revilla",
    "Jaime",
    "Antolín",
    "Cantos",
    "Ribes",
    "Montenegro",
    "Neira",
    "Fuente",
    "Flórez",
    "Hoyos",
    "Pellicer",
    "Jimeno",
    "Del Moral",
    "Ramiro",
    "Belda",
    "Silvestre",
    "Vico",
    "Caamaño",
    "Postigo",
    "Verdugo",
    "Piña",
    "Torralba",
    "Megías",
    "Zheng",
    "Sempere",
    "Farre",
];

const UN_APELLIDO = 1;
const DOS_APELLIDOS = 2;

const PERFIL = ["ADMIN", "GUEST", "ROOT", "USER"];

const PAISES = [
    "Afganistán",
    "Albania",
    "Alemania",
    "Andorra",
    "Angola",
    "Antigua y Barbuda",
    "Arabia Saudita",
    "Argelia",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaiyán",
    "Bahamas",
    "Bangladés",
    "Barbados",
    "Baréin",
    "Bélgica",
    "Belice",
    "Benín",
    "Bielorrusia",
    "Birmania",
    "Bolivia",
    "Bosnia y Herzegovina",
    "Botsuana",
    "Brasil",
    "Brunéi",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Bután",
    "Cabo Verde",
    "Camboya",
    "Camerún",
    "Canadá",
    "Catar",
    "Chad",
    "Chile",
    "China",
    "Chipre",
    "Ciudad del Vaticano",
    "Colombia",
    "Comoras",
    "Corea del Norte",
    "Corea del Sur",
    "Costa de Marfil",
    "Costa Rica",
    "Croacia",
    "Cuba",
    "Dinamarca",
    "Dominica",
    "Ecuador",
    "Egipto",
    "El Salvador",
    "Emiratos Árabes Unidos",
    "Eritrea",
    "Eslovaquia",
    "Eslovenia",
    "España",
    "Estados Unidos",
    "Estonia",
    "Etiopía",
    "Filipinas",
    "Finlandia",
    "Fiyi",
    "Francia",
    "Gabón",
    "Gambia",
    "Georgia",
    "Ghana",
    "Granada",
    "Grecia",
    "Guatemala",
    "Guyana",
    "Guinea",
    "Guinea ecuatorial",
    "Guinea-Bisáu",
    "Haití"
];
